name: Create Pull Request on Push to Dev

on:
  push:
    branches:
      - dev-branch

jobs:
  trigger_approval:
    runs-on: ubuntu-latest
   
    steps:
      - name: approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: CICD/CODEOWNERS
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

          
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: "Merge changes from dev to main"
          body: "This pull request merges changes from the dev branch to the main branch."
          
