name: Create Pull Request on Push to Dev

on:
  push:
    branches:
      - dev-branch

jobs:
  trigger_approval:
    runs-on: ubuntu-latest

    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: PremJonnavaram
          minimum-approvals: 1
          issue-title: "Merging dev-branch changes with main."
          issue-body: "Please approve or deny after reviewing the changes."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  create_pull_request_dev_to_main:
    needs: trigger_approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: "Merge changes from dev to main"
          body: "This pull request merges changes from the dev branch to the main branch."

  
