name: Create Pull Request on Push to Dev

on:
  push:
    branches:
      - dev-branch

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: "Merge changes from dev to main"
          body: "This pull request merges changes from the dev branch to the main branch."
          draft: false
          reviewers: codeowners
          labels: auto-merge

      - name: Merge Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash'
            });
