name: Create Pull Request on Push to Dev

on:
  push:
    branches:
      - main

jobs:

  create_pull_request_main_to_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          title: "Merge changes from dev to main"
          body: "This pull request merges changes from the dev branch to the main branch."
